// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package leviathan

import (
	"github.com/mostafasolati/leviathan/config"
	"github.com/mostafasolati/leviathan/contracts"
	"github.com/mostafasolati/leviathan/logger"
	"github.com/mostafasolati/leviathan/server"
)

// Injectors from main.go:

func Init(filename string) contracts.ILeviathan {
	iConfigService := config.NewConfigService(filename)
	iLogger := logger.NewLogger(iConfigService)
	iServerContainer := services.NewEchoServerContainer(iConfigService, iLogger)
	iLeviathan := NewLeviathan(iConfigService, iLogger, iServerContainer)
	return iLeviathan
}

// main.go:

type leviathan struct {
	config          contracts.IConfigService
	logger          contracts.ILogger
	serverContainer contracts.IServerContainer
}

func NewLeviathan(config2 contracts.IConfigService, logger2 contracts.ILogger,

	serverContainer contracts.IServerContainer,
) contracts.ILeviathan {
	return &leviathan{
		config: config2,
		logger: logger2,
	}
}

func (s *leviathan) Logger() contracts.ILogger {
	return s.logger
}

func (s *leviathan) Config() contracts.IConfigService {
	return s.config
}

func (s *leviathan) Server() contracts.IServerContainer {
	if s.serverContainer == nil {
		s.serverContainer = services.NewEchoServerContainer(s.config, s.logger)
	}
	return s.serverContainer
}
